import React from 'react';

export default function IndexSection__structures17() {
    return (
        <React.Fragment>
            <>
                <section data-from-ai="false" className="py-16 overflow-hidden ">  <div className="container px-4 mx-auto">    <div className="flex flex-wrap items-center -mx-4 mb-10">      <div className="w-full xl:w-2/3 px-4 mb-8 xl:mb-0">        <span className="text-sm font-semibold uppercase">Portfolio</span>        <h2 className="max-w-3xl font-heading text-3xl sm:text-4xl" cursor="shuffle-editor">Du moodboard au site performant</h2>    </div>      <div className="w-full xl:w-auto ml-auto px-4 xl:text-right"><a className="inline-block w-full sm:w-auto py-4 px-6 text-center font-heading font-medium text-base text-gray-900 hover:text-indigo-500 border border-gray-900 hover:border-indigo-500 rounded-sm transition duration-150" href="#">Réserver un audit</a></div>  </div>    <div className="mb-10">
      <a className="inline-block px-6 py-4 mr-2 font-heading rounded-full transition duration-300 bg-blue-700 text-white" href="#">Tous</a><a className="inline-block px-6 py-4 mr-2 font-heading rounded-full transition duration-300 hover:bg-blue-700 text-gray-900 border border-gray-200 hover:bg-blue-700 hover:text-white hover:border-transparent" href="#">Piscine - Spa</a><a className="inline-block px-6 py-4 mr-2 font-heading rounded-full transition duration-300 text-gray-900 border border-gray-200 hover:bg-blue-700 hover:text-white hover:border-transparent" href="#">Immobilier</a>
    </div>    <div className="flex flex-wrap -mx-4">      <div className="w-full lg:w-1/2 px-4 mb-8 lg:mb-0">        <div className="flex flex-wrap -mx-4">          <div className="w-full sm:w-1/2 px-4 mb-8">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-ef638fd08a94a6e4d06f02316eb0da90.jpg" alt cursor="shuffle-editor" />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Brand24</a>            </div>          </div>        </div>          <div className="w-full sm:w-1/2 px-4 mb-8">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-44d1e2781b284d3232af5db90a190c37.jpg" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Brand24</a>            </div>          </div>        </div>          <div className="w-full px-4">            <div className="relative flex items-end p-6 rounded overflow-hidden h-96">              <img className="absolute top-0 left-0 w-full h-full object-cover h-96" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/desktop-Organic-food-papilles-mockup-009-min.png" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-3xl text-white hover:underline" href="#">Neonic</a>            </div>          </div>        </div>      </div>    </div>      <div className="w-full lg:w-1/2 px-4">        <div className="flex flex-wrap -mx-4">          <div className="w-full px-4 mb-8">            <div className="relative flex items-end p-6 rounded overflow-hidden h-96">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/naoya-breizh-sushi.jpg" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-3xl text-white hover:underline" href="#">Sheridan</a>            </div>          </div>        </div>          <div className="w-full sm:w-1/2 px-4 mb-8 sm:mb-0">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-8a89c7537d20126b4f65a213f328e89e.png" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Klakier</a>            </div>          </div>        </div>          <div className="w-full sm:w-1/2 px-4">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-4cb71fb3269ae71d6888b2032d530cf0.png" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Brand24</a>            </div>          </div>        </div>      </div>    </div>  </div>    <div className="flex-wrap -mx-4 hidden">      <div className="w-full lg:w-1/2 px-4 mb-8 lg:mb-0">        <div className="flex flex-wrap -mx-4">          <div className="w-full sm:w-1/2 px-4 mb-8">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/desktop-Organic-food-papilles-mockup-009-min.png" alt cursor="shuffle-editor" />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Brand24</a>            </div>          </div>        </div>          <div className="w-full sm:w-1/2 px-4 mb-8">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-44d1e2781b284d3232af5db90a190c37.jpg" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Brand24</a>            </div>          </div>        </div>          <div className="w-full px-4">            <div className="relative flex items-end h-140 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-ef638fd08a94a6e4d06f02316eb0da90.jpg" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-3xl text-white hover:underline" href="#">Neonic</a>            </div>          </div>        </div>      </div>    </div>      <div className="w-full lg:w-1/2 px-4">        <div className="flex flex-wrap -mx-4">          <div className="w-full px-4 mb-8">            <div className="relative flex items-end h-140 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-8e23271557168ca882275f9e454bae85.png" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-3xl text-white hover:underline" href="#">Sheridan</a>            </div>          </div>        </div>          <div className="w-full sm:w-1/2 px-4 mb-8 sm:mb-0">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-8a89c7537d20126b4f65a213f328e89e.png" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Klakier</a>            </div>          </div>        </div>          <div className="w-full sm:w-1/2 px-4">            <div className="relative flex items-end h-72 p-6 rounded overflow-hidden">              <img className="absolute top-0 left-0 w-full h-full object-cover" src="https://static.shuffle.dev/uploads/files/c9/c92bf0a83b0e3f1d28caf7c9c05d33704a901e05/original-4cb71fb3269ae71d6888b2032d530cf0.png" alt />              <div className="relative">                <div className="mb-2">
                  <a className="inline-block font-heading text-white hover:text-gray-100 mr-4" href="#">#people</a><a className="inline-block font-heading text-white hover:text-gray-100" href="#">#family</a>
                </div>                <a className="font-heading text-lg text-white hover:underline" href="#">Brand24</a>            </div>          </div>        </div>      </div>    </div>  </div></div></section>


            </>
        </React.Fragment>
    );
}

